spring:
  application:
    name: member
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc-member?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
server:
  port: 8000
